require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GamelobbiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Gamelobby. As you add validations to Gamelobby, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GamelobbiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all gamelobbies as @gamelobbies" do
      gamelobby = Gamelobby.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:gamelobbies)).to eq([gamelobby])
    end
  end

  describe "GET #show" do
    it "assigns the requested gamelobby as @gamelobby" do
      gamelobby = Gamelobby.create! valid_attributes
      get :show, {:id => gamelobby.to_param}, valid_session
      expect(assigns(:gamelobby)).to eq(gamelobby)
    end
  end

  describe "GET #new" do
    it "assigns a new gamelobby as @gamelobby" do
      get :new, {}, valid_session
      expect(assigns(:gamelobby)).to be_a_new(Gamelobby)
    end
  end

  describe "GET #edit" do
    it "assigns the requested gamelobby as @gamelobby" do
      gamelobby = Gamelobby.create! valid_attributes
      get :edit, {:id => gamelobby.to_param}, valid_session
      expect(assigns(:gamelobby)).to eq(gamelobby)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Gamelobby" do
        expect {
          post :create, {:gamelobby => valid_attributes}, valid_session
        }.to change(Gamelobby, :count).by(1)
      end

      it "assigns a newly created gamelobby as @gamelobby" do
        post :create, {:gamelobby => valid_attributes}, valid_session
        expect(assigns(:gamelobby)).to be_a(Gamelobby)
        expect(assigns(:gamelobby)).to be_persisted
      end

      it "redirects to the created gamelobby" do
        post :create, {:gamelobby => valid_attributes}, valid_session
        expect(response).to redirect_to(Gamelobby.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved gamelobby as @gamelobby" do
        post :create, {:gamelobby => invalid_attributes}, valid_session
        expect(assigns(:gamelobby)).to be_a_new(Gamelobby)
      end

      it "re-renders the 'new' template" do
        post :create, {:gamelobby => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gamelobby" do
        gamelobby = Gamelobby.create! valid_attributes
        put :update, {:id => gamelobby.to_param, :gamelobby => new_attributes}, valid_session
        gamelobby.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested gamelobby as @gamelobby" do
        gamelobby = Gamelobby.create! valid_attributes
        put :update, {:id => gamelobby.to_param, :gamelobby => valid_attributes}, valid_session
        expect(assigns(:gamelobby)).to eq(gamelobby)
      end

      it "redirects to the gamelobby" do
        gamelobby = Gamelobby.create! valid_attributes
        put :update, {:id => gamelobby.to_param, :gamelobby => valid_attributes}, valid_session
        expect(response).to redirect_to(gamelobby)
      end
    end

    context "with invalid params" do
      it "assigns the gamelobby as @gamelobby" do
        gamelobby = Gamelobby.create! valid_attributes
        put :update, {:id => gamelobby.to_param, :gamelobby => invalid_attributes}, valid_session
        expect(assigns(:gamelobby)).to eq(gamelobby)
      end

      it "re-renders the 'edit' template" do
        gamelobby = Gamelobby.create! valid_attributes
        put :update, {:id => gamelobby.to_param, :gamelobby => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested gamelobby" do
      gamelobby = Gamelobby.create! valid_attributes
      expect {
        delete :destroy, {:id => gamelobby.to_param}, valid_session
      }.to change(Gamelobby, :count).by(-1)
    end

    it "redirects to the gamelobbies list" do
      gamelobby = Gamelobby.create! valid_attributes
      delete :destroy, {:id => gamelobby.to_param}, valid_session
      expect(response).to redirect_to(gamelobbies_url)
    end
  end

end
